#! /bin/sh

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config bottom_padding 42

bspc config external_rules_command ~/.config/bspwm/external_rules

bspc monitor -d "   " "   " "   " "   "

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a *:crx_nckgahadagoaajjgafhacjanaoiihapd state=floating
